<?php
/**
 * Functions.php contains all the core functions for your theme to work properly.
 * Please do not edit this file!!
 *
 * @package Thoughts WordPress Theme
 * @since 1.0
 * @author AJ Clarke : http://wpexplorer.com
 * @copyright Copyright (c) 2012, AJ Clarke
 * @link http://wpexplorer.com
 * @license http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */


// Define Constants
define( 'WPEX_JS_DIR', get_template_directory_uri().'/js' );
define( 'WPEX_CSS_DIR', get_template_directory_uri().'/css' );


// Theme Setup
if ( !function_exists( 'wpex_setup' ) ) {
	function wpex_setup() {

		//default width of primary content area
		$content_width = 945;
		
		//theme support
		add_theme_support('automatic-feed-links');
		add_theme_support('custom-background');
		add_theme_support('post-thumbnails');
		
		//register navigation menus
		register_nav_menus ( array(
			'main_menu' => __( 'Main Menu', 'wpex' )
		) );

		// Add Post Formats Support
		add_theme_support( 'post-formats', array( 'video', 'quote', 'link', 'audio', 'image', 'gallery' ) );

		//Localization support
		load_theme_textdomain( 'wpex', get_template_directory() .'/lang' );

	}
}
add_action( 'after_setup_theme', 'wpex_setup' );


// TGM Plugin Activation => https://github.com/thomasgriffin/TGM-Plugin-Activation
require_once ( get_template_directory() .'/functions/recommend-plugins.php' );


// Includes
require_once( get_template_directory() .'/functions/scripts.php' );
require_once ( get_template_directory() .'/functions/hooks.php' );
require_once( get_template_directory() .'/functions/theme_customizer.php' );
require_once( get_template_directory() .'/functions/font_awesome.php' );
require_once( get_template_directory() .'/functions/pagination.php' );
require_once( get_template_directory() .'/functions/img_resizer.php' );
require_once( get_template_directory() .'/functions/img_defaults.php' );
require_once( get_template_directory() .'/functions/wpex_comments_output.php' );

if( is_admin( )) {
	require_once( get_template_directory() .'/functions/gallery-metabox/gmb-admin.php' );
	require_once( get_template_directory() .'/functions/post_meta.php' );
	require_once( get_template_directory() .'/functions/dashboard-feed.php' );
	require_once( get_template_directory() .'/functions/welcome.php' );
} else {
	require_once( get_template_directory() .'/functions/gallery-metabox/gmb-display.php' );
}


// Image caption
if ( !function_exists( 'wpex_post_feat_img_caption' ) ) :
	function wpex_post_feat_img_caption() {
		global $post;
		$thumbnail_image = get_posts( array( 'p' => get_post_thumbnail_id( get_the_ID() ), 'post_type' => 'attachment') );
		if ( $thumbnail_image[0]->post_content !== '' ) {
			echo '<p class="single-portfolio-image-description clearfix">'.$thumbnail_image[0]->post_content.'</p>';
		}
	}
endif;

// Change default read more style
if ( !function_exists( 'wpex_new_excerpt_more' ) ) {
	function wpex_new_excerpt_more($more) {
		global $post;
		return '...';
	}
}
add_filter('excerpt_more', 'wpex_new_excerpt_more');

// Change default excerpt length
if ( !function_exists( 'wpex_custom_excerpt_length' ) ) {
	function wpex_custom_excerpt_length( $length ) {
		return get_theme_mod( 'wpex_excerpt_length', '30' );
	}
}
add_filter( 'excerpt_length', 'wpex_custom_excerpt_length', 999 );



// ALl you can search even custom post START **************************************************************
/**
 * Extend WordPress search to include custom fields 
 * http://adambalee.com
 *以下サイト参照してコピペ
 https://gakuya.work/wordpress_search_customfield/
 */
/**
 * Join posts and postmeta tables
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_join
 */
function cf_search_join($join) {
    global $wpdb;
    if (is_search()) {
        $join .=' LEFT JOIN '.$wpdb->postmeta. ' ON '. $wpdb->posts . '.ID = ' . $wpdb->postmeta . '.post_id ';
    }
    return $join;
}
add_filter('posts_join', 'cf_search_join');

/**
 * Modify the search query with posts_where
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_where
 */
function cf_search_where($where) {
    global $wpdb;
    if (is_search()) {
        $where = preg_replace(
            "/\(\s*".$wpdb->posts.".post_title\s+LIKE\s*(\'[^\']+\')\s*\)/",
            "(".$wpdb->posts.".post_title LIKE $1) OR (".$wpdb->postmeta.".meta_value LIKE $1)", $where);
    }
    return $where;
}
add_filter('posts_where', 'cf_search_where');

/**
 * Prevent duplicates
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_distinct
 */
function cf_search_distinct($where) {
    global $wpdb;
    if (is_search()) {
        return "DISTINCT";
    }
    return $where;
}
add_filter('posts_distinct', 'cf_search_distinct');

//stop using WP jquery
add_action('wp_print_scripts','my_deregister_script',100);
function my_deregister_script() {
wp_deregister_script('jquery');
}

/* 【管理画面】管理画面にもファビコンを表示 */
function admin_favicon() {
 echo '<link rel="shortcut icon" type="image/x-icon" href="/en/blog/wp-content/themes/wpex-thoughts/images/favicon-blog-EN.ico" />';
}
add_action('admin_head', 'admin_favicon');

//新規投稿に初期値を入力
function my_default_title( $post_title, $post ){
    if( $post->post_type == 'post' ){
        $post_title = get_the_date();
    } 
      return $post_title;
}
add_filter( 'default_title', 'my_default_title', 10, 2 );

function my_default_content( $post_content, $post ){
    if( $post->post_type == 'post' ){
        $post_content = '<p style="color:#c00;text-align:center;">*Before correction</p>';
    }
    return $post_content;
}
add_filter( 'default_content', 'my_default_content', 10, 2 );

// ALl you can search even custom post END **************************************************************

/** Undisplay PHP error due to update for PHP version */
error_reporting(0);
