<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-59FKPF7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="head"><h2 id="logotype"><a href="/" class="std"><img src="/images/common/site-logo.png" alt="料理、食をテーマに作品を制作する現代美術家/新宅睦仁/シンタクトモニ"></a><a href="/en<?php echo $_SERVER['PHP_SELF'] ?>" id="en-link" class="std"><img src="/images/common/head-lang_jp.png" alt="website-for-english"></a><a href="/blog/" class="blog"><img src="/images/common/head_pic_blog.png" alt="現代美術家/新宅睦仁/シンタクトモニのエッセイ・コラムのブログ"></a></h2><div id="dl-menu" class="dl-menuwrapper"><button class="dl-trigger">Open Menu</button><ul class="dl-menu" itemscope itemtype="http://www.schema.org/SiteNavigationElement"><!--li class="home"><a href="/">ホーム</a><a href="/en<?php echo $_SERVER['PHP_SELF'] ?>">ENGLISH<br>Version</a></li--><li itemprop="name" class="news"><a itemprop="URL" href="/news">ニュース</a><?php require_once dirname(__FILE__).'/../blog/wp-load.php'; $page_id = 7229; $content = get_page($page_id); echo $content->post_content; ?></li><li itemprop="name"><a itemprop="URL" href="/about">経歴</a></li><li itemprop="name"><a itemprop="URL" href="/works">作品</a></li><li itemprop="name"><a itemprop="URL" href="/works/exhibition/">展覧会</a></li><li itemprop="name"><a itemprop="URL" href="/blog/amp">ブログ</a></li><li itemprop="name"><a itemprop="URL" href="/en/blog/amp">BLOG in English(毎日更新)</a></li><li itemprop="name"><a itemprop="URL" href="/contact">お問い合わせ</a></li><li class="sns" itemprop="name"><ul><?php $sns = file_get_contents('https://tomonishintaku.com/inc/sns.php'); echo $sns; ?></ul>
<li class="lang-switch" itemprop="name">
	<a itemprop="URL" href="/en<?php echo $_SERVER['PHP_SELF'] ?>" class="common-nav en">English</a><a href="/en/blog/" class="blog-nav">English</a>
	<span class="common-nav">Japanese</span><span class="blog-nav">Japanese</span>
</li>
</ul></div><?php $path = $_SERVER['SCRIPT_NAME']; if ( $path == '/index.html' ) { $h_tag = '<h1 class="std">食（料理・食文化）をテーマに、絵画やインスタレーションによる現代アートの制作活動を行う美術家/新宅睦仁</h1>';}else{ $h_tag = '<h2 class="std">食をテーマに、絵画やインスタレーションによる現代アートの制作活動を行う美術家/新宅睦仁</h2>';}?><?php echo $h_tag; ?></div><div id="gnav"><ul id="global_navi" class="clearfix" itemscope itemtype="http://www.schema.org/SiteNavigationElement"><li itemprop="name"><a href="/news" itemprop="URL">ニュース</a></li><li itemprop="name"><a itemprop="URL" href="/about">経歴</a></li><li itemprop="name"><a itemprop="URL" href="/works">作品</a></li><li itemprop="name"><a itemprop="URL" href="/exhibition/">展覧会</a></li><li itemprop="name"><a itemprop="URL" href="/blog/">ブログ</a></li><li itemprop="name"><a itemprop="URL" href="/contact">お問い合わせ</a></li></ul>
<a href="/news"><div class="pc-line-news"><?php $page_id = 7229; $content = get_page($page_id); echo $content->post_content; ?></span></div></a></div>
